### ISSUE TITLE
Problem using regex

### ISSUE THREAD

**Issue by Fenixin** [ivandokov/phockup#39]
Hello!

I'm having some issues using the option --regex. I'm pretty new to regex and I'm probably the problem here, but I would really appreciate some help.

The regular expression I'm using is: 

`"img[_-]?(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})[_-]?"`

And some of the file names store in the folder are:
```
img-20161026-wa0011.jpg
img-20161026-wa0012.jpg
img-20161026-wa0013.jpg
img-20161101-wa0001.jpg
```
I also tried to use a regex tester like [this one](https://regex101.com/) and it seems to confirm that my expression is correct.

The command used to run phockup is:
`./phockup.py ~/Escritorio/notscanned/ ~/Escritorio/phockup-test/ -m -d YYYY-MM-DD -r="img[_-]?(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})[_-]?"`

And with all this phockup only moves the pictures to the unknown folder:

> /home/alejandro/Escritorio/notscanned/img-20161101-wa0001.jpg => /home/alejandro/Escritorio/phockup-test/unknown/img-20161101-wa0001.jpg

What am I doing wrong? Any help would be appreciated.

Thanks!

**Comment by ivandokov** [comment]
Hello @Fenixin.

Actually the regex is not correct since it is not matching the whole file name.

Try this one, it should be working:
```
img[_-]?(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})[_-](.*)?
```

**Comment by Fenixin** [comment]
Thanks for the fast answer.

Still no luck. Using:
`phockup ~/Escritorio/unknown2/ ~/Escritorio/phockup-test/ -m -d YYYY-MM-DD -r="img[_-]?(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})[_-](.*)?"`

phockup says:
> /home/alejandro/Escritorio/notscanned/img-20161213-wa0008.jpg => /home/alejandro/Escritorio/phockup-test/unknown/img-20161213-wa0008.jpg

**Comment by ivandokov** [comment]
I will have to take a closer look at this, but unfortunately I am busy now. 
Will do my best to get back to you as soon as possible.

**Comment by Fenixin** [comment]
Thanks very much. If you need something to diagnose the problem just tell me.

**Comment by ivandokov** [comment]
I did some tests with the test file `unknown.jpg` which is not having the proper exif data. I renamed it to `img-20161026-wa0011.jpg` and tried the command below and it worked as expected.
```phockup input output -m -d YYYY-MM-DD -r="img[_-]?(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})[_-](.*)?"```

I cannot seem to reproduce your issue. Can you please provide one of your images, if that's OK with you so I can try to reproduce the issue.

**Comment by Fenixin** [comment]
Here you have it: https://www.dropbox.com/s/ysa5mghw0jt2g3v/img-20160308-wa0002.jpg?dl=0

Some additional information: I'm using Ubuntu 16.04, I have tried downloading the repository and installing it from snap.

**Comment by ivandokov** [comment]
@pauloup I think your idea for the subseconds regex extraction is good. Do you mind making a PR with this implemented?
